[package]
name = "clash-tray"
version = "0.1.0"
edition = "2024"

[dependencies]
async-io = "2"
async-web-client = { version = "0.6.3", default-features = false, features = ["json", "ring", "tls12"] }
futures-channel = "0.3"
futures-lite = "2"
http = "1.0.0"
ksni = { version = "0.3.6", default-features = false, features = ["async-io"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
